apiVersion: apps/v1
kind: Deployment
metadata:
 name: capstone-deployment
 labels:
  app: capstone

spec:
 replicas: 2
 
 selector:
  matchLabels:
   app: capstone
 
 template:
  metadata:
   labels:
    app: capstone
  
  spec:
   containers:
   - name: capstone-container
     image: officialamit1232/capstone:latest
     ports:
     - containerPort: 80
